version: '3'
services:
  api:
    build: .
    volumes:
      - .:/usr/src/api
      - /usr/src/api/node_modules
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: localenv
    networks:
      - localnet
    depends_on:
      - db
  db:
    image: postgres:9.6
    volumes:
    - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - localnet

volumes:
  dbdata:

networks:
  localnet: